package hotel;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JAZTIN
 */
public class management extends javax.swing.JFrame {

    /**
     * Creates new form management
     */
    public management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Costumer = new javax.swing.JTextField();
        Nationality = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        CID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        COD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        type = new javax.swing.JTextField();
        RNO = new javax.swing.JTextField();
        REN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cutomer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell", 0, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Costumer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 209, 29));
        jPanel1.add(Nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 209, 29));
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 209, 29));
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 209, 29));
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 209, 29));
        jPanel1.add(CID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 209, 29));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel2.setText(" COstumer ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel5.setText("Nationality");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel6.setText("Prove of ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel7.setText("Contact/email");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel8.setText("Checked In Date");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 22));
        jPanel1.add(COD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 209, 29));

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel9.setText("Checked Out Date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 22));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 460));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Room Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell", 0, 24))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel3.setText("Room type");

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel10.setText("RooM NO");

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel11.setText("Room Ext NO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(REN, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RNO, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(63, 63, 63)
                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel10))
                    .addComponent(RNO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(REN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 490, 290));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Name", "Nationality", "Prove of ID", "Contact/Email", "Checked IN", "Checked OUt", "Room NO", "Room Type", "Room EXT NO"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 16, 500, 590));

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 690, 140, 50));

        jButton2.setText("New Customer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 620, 130, 50));

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 620, 130, 50));

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 620, 140, 50));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (Costumer.getText().equals("")||Name.getText().equals("")||Nationality.getText().equals("")||ID.getText().equals("")||contact.getText().equals("")
                ||CID.getText().equals("")||COD.getText().equals("")||type.getText().equals("")||RNO.getText().equals("")||REN.getText().equals("")){
                 JOptionPane.showMessageDialog(this,"fill up all field" );
           }
           else{
                 String data[]={Costumer.getText(),Name.getText(),Nationality.getText(),ID.getText(),contact.getText(),
                     CID.getText(),COD.getText(),type.getText(),RNO.getText(),REN.getText()};
           
            {  
            DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
            tblModel.addRow(data);
         
            JOptionPane.showMessageDialog(this,"Added Succesfully" );
                   }
          Costumer.setText("");
          Name.setText("");
          Nationality.setText("");
          ID.setText("");
          contact.setText("");
          CID.setText("");
          COD.setText("");                 
          type.setText(""); 
          RNO.setText(""); 
          REN.setText("");     
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Confirm to exit","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        if(jTable1.getSelectedRowCount()==1){
            tblModel.removeRow(jTable1.getSelectedRow());
          Costumer.setText("");
          Name.setText("");
          Nationality.setText("");
          ID.setText("");
          contact.setText("");
          CID.setText("");
          COD.setText("");                 
          type.setText(""); 
          RNO.setText(""); 
          REN.setText(""); 
        }
        else{
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Table is Empty" );
            }else{
                JOptionPane.showMessageDialog(this,"Select Single row to Delete");
            }
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
       if(jTable1.getSelectedRowCount() ==1){
           
            
            String cst = Costumer.getText();
            String name = Name.getText();
            String nationality =  Nationality.getText();
            String id = ID.getText();
            String Contact = contact.getText();
            String in = CID.getText();
            String out = COD.getText();
            String Rt = type.getText();
            String RN = RNO.getText();
            String ren = REN.getText();
              
            
             tblModel.setValueAt(cst, jTable1.getSelectedRow(), 0);
             tblModel.setValueAt(name, jTable1.getSelectedRow(), 1);
             tblModel.setValueAt(nationality, jTable1.getSelectedRow(), 2);
             tblModel.setValueAt(id, jTable1.getSelectedRow(), 3);
             tblModel.setValueAt(Contact , jTable1.getSelectedRow(), 4);
             tblModel.setValueAt(in, jTable1.getSelectedRow(), 5);
             tblModel.setValueAt(out, jTable1.getSelectedRow(), 6);
             tblModel.setValueAt(Rt, jTable1.getSelectedRow(), 7);
             tblModel.setValueAt(RN, jTable1.getSelectedRow(), 8);
             tblModel.setValueAt(ren, jTable1.getSelectedRow(), 9);
              JOptionPane.showMessageDialog(this,"Updated" );
          Costumer.setText("");
          Name.setText("");
          Nationality.setText("");
          ID.setText("");
          contact.setText("");
          CID.setText("");
          COD.setText("");                 
          type.setText(""); 
          RNO.setText(""); 
          REN.setText(""); 
        }else{
            if(jTable1.getRowCount()==0){
              
                JOptionPane.showMessageDialog(this,"Table is Empty!");
            }else{
               
                JOptionPane.showMessageDialog(this,"Select sngle row to update!");
            }
    }//GEN-LAST:event_jButton4ActionPerformed
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
         String a = tblModel.getValueAt(jTable1.getSelectedRow(),0).toString();
         String b = tblModel.getValueAt(jTable1.getSelectedRow(),1).toString();
         String c = tblModel.getValueAt(jTable1.getSelectedRow(),2).toString();
         String d = tblModel.getValueAt(jTable1.getSelectedRow(),3).toString();
         String e = tblModel.getValueAt(jTable1.getSelectedRow(),4).toString();
         String f = tblModel.getValueAt(jTable1.getSelectedRow(),5).toString();
         String g = tblModel.getValueAt(jTable1.getSelectedRow(),6).toString();
         String h = tblModel.getValueAt(jTable1.getSelectedRow(),7).toString();
         String i = tblModel.getValueAt(jTable1.getSelectedRow(),8).toString();
         String j = tblModel.getValueAt(jTable1.getSelectedRow(),9).toString();
         
         //set to textfield
         Costumer.setText(a);
           Name.setText(b);
            Nationality.setText(c);
            ID.setText(d);
            contact.setText(e);
            CID.setText(f);
            COD.setText(g);
            type.setText(h);
            RNO.setText(i);
            REN.setText(j);

    }//GEN-LAST:event_jTable1MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CID;
    private javax.swing.JTextField COD;
    private javax.swing.JTextField Costumer;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Nationality;
    private javax.swing.JTextField REN;
    private javax.swing.JTextField RNO;
    private javax.swing.JTextField contact;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
